//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá dữ liệu thất bại! Vui lòng thử lại sau hoặc liên hệ MISA để được trợ giúp!.
        /// </summary>
        internal static string VN_ErrDel {
            get {
                return ResourceManager.GetString("VN.ErrDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thất bại! Vui lòng thử lại sau hoặc liên hệ MISA để được trợ giúp!.
        /// </summary>
        internal static string VN_ErrInsert {
            get {
                return ResourceManager.GetString("VN.ErrInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải dữ liệu! Vui lòng thử lại sau hoặc liên hệ MISA để được trợ giúp!.
        /// </summary>
        internal static string VN_ErrLoad {
            get {
                return ResourceManager.GetString("VN.ErrLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sảy ra lỗi trong quá trình tìm kiếm. Vui lòng thử lại sau!.
        /// </summary>
        internal static string VN_ErrSearch {
            get {
                return ResourceManager.GetString("VN.ErrSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại! Vui lòng thử lại sau hoặc liên hệ MISA để được trợ giúp!.
        /// </summary>
        internal static string VN_ErrUpdate {
            get {
                return ResourceManager.GetString("VN.ErrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá dữ liệu thành công!.
        /// </summary>
        internal static string VN_SuccessDel {
            get {
                return ResourceManager.GetString("VN.SuccessDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công!.
        /// </summary>
        internal static string VN_SuccessInsert {
            get {
                return ResourceManager.GetString("VN.SuccessInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải dữ liệu thành công!.
        /// </summary>
        internal static string VN_SuccessLoad {
            get {
                return ResourceManager.GetString("VN.SuccessLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm thành công!.
        /// </summary>
        internal static string VN_SuccessSearch {
            get {
                return ResourceManager.GetString("VN.SuccessSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        internal static string VN_SuccessUpdate {
            get {
                return ResourceManager.GetString("VN.SuccessUpdate", resourceCulture);
            }
        }
    }
}
